from sqlalchemy import Column, String, Boolean, Numeric, Integer, DateTime, text, ForeignKey
from sqlalchemy.dialects.postgresql import UUID, ARRAY
from app.models.base import Base

class Order(Base):
    __tablename__ = 'orders'
    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text('gen_random_uuid()'))
    code = Column(String, nullable=False)
    client_id = Column(UUID(as_uuid=True), ForeignKey('clients.id', ondelete='CASCADE'), nullable=False)
    phone = Column(String, nullable=False)
    street = Column(String, nullable=False)
    reference = Column(String, nullable=True, default='')
    district = Column(String, nullable=False)
    neighborhood = Column(String, nullable=True, default='')
    lat = Column(Numeric, nullable=False, default=0)
    lng = Column(Numeric, nullable=False, default=0)
    indications = Column(String, nullable=True, default='')
    access_type = Column(String, nullable=False, default='Fácil')
    delivery_date = Column(String, nullable=False)
    time_window_start = Column(String, nullable=False)
    time_window_end = Column(String, nullable=False)
    priority = Column(String, nullable=False, default='medium')
    weight_kg = Column(Numeric, nullable=False, default=0)
    volume_m3 = Column(Numeric, nullable=False, default=0)
    product_type = Column(String, nullable=False, default='Abarrotes')
    observations = Column(String, nullable=True, default='')
    status = Column(String, nullable=False, default='pending')
    preferred_time = Column(String, nullable=False, default='09:00')
    pref_time_window_start = Column(String, nullable=False, default='09:00')
    pref_time_window_end = Column(String, nullable=False, default='12:00')
    restrictions = Column(ARRAY(String), nullable=False, server_default='{}')
    requires_special_attention = Column(Boolean, nullable=False, default=False)
    no_lunch_hours = Column(Boolean, nullable=False, default=False)
    requires_phone_coordination = Column(Boolean, nullable=False, default=False)
    pref_observations = Column(String, nullable=True, default='')
    route_id = Column(String, nullable=True)
    delivery_order = Column(Integer, nullable=True)
    driver_id = Column(UUID(as_uuid=True), nullable=True)
    delivered_at = Column(DateTime(timezone=True), nullable=True)
    incident_reason = Column(String, nullable=True)
    incident_notes = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=text('now()'))